packages:
  - frontend
  - backend
  - shared
onlyBuiltDependencies:
  - esbuild
  - ffmpeg-static
  - sharp
allowBuilds:
  esbuild: set this to true or false
  ffmpeg-static: set this to true or false
  sharp: set this to true or false
