import { randomBytes, randomUUID } from "node:crypto";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import cookieParser from "cookie-parser";
import express, { type NextFunction, type Request, type Response } from "express";
import helmet from "helmet";
import { z } from "zod";
import { CHALLENGE_TTL_MS, COPY, KASPA_TESTNET_ADDRESS_PATTERN, mediaHintError, NETWORK, normalizeDisplayName, normalizePostText, parseKasToSompi, PREPARED_TTL_MS, SESSION_IDLE_TTL_MS, validateDisplayName, type MembershipAddressVerificationResponse, type PostResponse } from "@onlykas/shared";
import type { CreatorCovenant, MembershipGateway, MembershipVerifier, ObjectStorage, PaymentGateway, Post, PreparedMembershipRecord, PreparedPaymentRecord, Profile, Session, Store, WalletVerifier } from "./domain.js";
import { safeError, logger as defaultLogger, requestId, type Logger } from "./observability.js";
import { MediaValidationError, verifyMediaFile } from "./media.js";

const sessionCookie="onlykas_session"; const addressPattern=KASPA_TESTNET_ADDRESS_PATTERN;
export interface AppDependencies { store: Store; storage: ObjectStorage; walletVerifier: WalletVerifier; paymentGateway?: PaymentGateway; membershipGateway?: MembershipGateway; membershipVerifier?: MembershipVerifier; publicOrigin: string; production?: boolean; now?:()=>number; readinessCheck?:()=>boolean|Promise<boolean>; logger?:Logger; }
declare global {
  // Express request augmentation is required by the auth middleware.
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace Express { interface Request { walletSession?: Session; requestId: string; } }
}

export function createApp(d: AppDependencies) {
   const app=express(); const now=d.now??Date.now; const logger=d.logger??defaultLogger;
  // TODO(remove): superseded by the store-backed prepared_payments/prepared_memberships tables.
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const preparedPayments=new Map<string, PreparedPaymentRecord>(); const preparedMemberships=new Map<string,PreparedMembershipRecord>();
  app.disable("x-powered-by"); app.use((req,res,next)=>{req.requestId=requestId(req.get("x-request-id"));res.setHeader("X-Request-Id",req.requestId);const startedAt=Date.now();res.on("finish",()=>{if(req.path.startsWith("/api/")){const write=res.statusCode>=500?logger.error:res.statusCode>=400?logger.warn:logger.info;write("request_completed",{requestId:req.requestId,method:req.method,path:req.path,route:routePattern(req),statusCode:res.statusCode,durationMs:Date.now()-startedAt,authenticated:Boolean(req.walletSession),...(res.locals.apiErrorCode?{errorCode:res.locals.apiErrorCode}:{}),...(req.params?.id?{postId:req.params.id}: {})});}});next();}); app.use(helmet({contentSecurityPolicy:false})); app.use(express.json({limit:"1mb"})); app.use(cookieParser());
  app.get("/healthz",(_,res)=>res.json({status:"ok"})); app.get("/readyz",asyncHandler(async(_,res)=>{const ready=await(d.readinessCheck?.()??true);res.status(ready?200:503).json({status:ready?"ok":"unready"});}));
  async function optional(req:Request,res:Response,next:NextFunction){try{const id=req.cookies[sessionCookie] as string|undefined;if(!id)return next();const session=await d.store.getSession(id,now());if(!session){res.clearCookie(sessionCookie);return next();}const expiresAt=now()+SESSION_IDLE_TTL_MS;await d.store.rollSession(id,expiresAt);req.walletSession={...session,expiresAt};setCookie(res,id,Boolean(d.production));next();}catch(e){next(e);}}
  const required=(req:Request,res:Response,next:NextFunction)=>req.walletSession?next():apiError(res,401,"AUTHENTICATION_REQUIRED");
  app.post("/api/auth/challenge",asyncHandler(async(req,res)=>{const b=z.object({address:z.string().regex(addressPattern)}).parse(req.body);trusted(req,d.publicOrigin);await d.store.pruneChallenges(now());const issued=now(),id=randomUUID(),nonce=randomBytes(32).toString("hex"),message=`${COPY.authPrompt}\n\nWallet: ${b.address}\nNetwork: ${NETWORK}\nOrigin: ${d.publicOrigin}\nNonce: ${nonce}`;await d.store.createChallenge({id,nonce,address:b.address,origin:d.publicOrigin,network:NETWORK,message,expiresAt:issued+CHALLENGE_TTL_MS,consumedAt:null});res.status(201).json({challengeId:id,message,expiresAt:new Date(issued+CHALLENGE_TTL_MS).toISOString()});}));
  app.post("/api/auth/session",asyncHandler(async(req,res)=>{trusted(req,d.publicOrigin);await d.store.pruneSessions(now());const b=z.object({challengeId:z.string().uuid(),address:z.string().regex(addressPattern),publicKey:z.string().regex(/^[0-9a-fA-F]{64,66}$/),signature:z.string().min(1)}).parse(req.body);const c=await d.store.consumeChallenge(b.challengeId,now());if(!c||c.address!==b.address||c.origin!==d.publicOrigin||c.network!==NETWORK||!(await d.walletVerifier.verify(c.message,b.signature,b.publicKey,b.address)))return res.status(401).json({error:"WALLET_VERIFICATION_FAILED",message:COPY.verificationFailed});const session={id:randomBytes(32).toString("base64url"),address:b.address,expiresAt:now()+SESSION_IDLE_TTL_MS};await d.store.createSession(session);setCookie(res,session.id,Boolean(d.production));res.status(201).json({address:session.address,expiresAt:new Date(session.expiresAt).toISOString()});}));
  app.get("/api/auth/session",optional,asyncHandler(async(req,res)=>{if(!req.walletSession)return apiError(res,401,"AUTH_REQUIRED");res.json({address:req.walletSession.address,displayName:(await d.store.getProfile(req.walletSession.address))?.displayName??null,expiresAt:new Date(req.walletSession.expiresAt).toISOString()});}));
  app.post("/api/auth/logout",optional,asyncHandler(async(req,res)=>{const id=req.cookies[sessionCookie] as string|undefined;if(id)await d.store.deleteSession(id);res.clearCookie(sessionCookie,cookieOptions(Boolean(d.production)));res.status(204).end();}));
  app.get("/api/profile",optional,required,asyncHandler(async(req,res)=>res.json(profileResponse(await d.store.getProfile(req.walletSession!.address),req.walletSession!.address))));
  app.put("/api/profile",optional,required,asyncHandler(async(req,res)=>{const b=z.object({displayName:z.string().max(80)}).parse(req.body),name=normalizeDisplayName(b.displayName);if([...name].length>40)return apiError(res,400,"INVALID_DISPLAY_NAME");const profile:Profile={address:req.walletSession!.address,displayName:validateDisplayName(name),updatedAt:now()};await d.store.saveProfile(profile);res.json(profileResponse(profile,profile.address));}));
  app.get("/api/creators/search",asyncHandler(async(req,res)=>{const q=z.string().trim().min(1).max(40).parse(req.query.q);res.json((await d.store.searchCreators(q,20)).map(p=>({address:p.address,displayAddress:shorten(p.address),displayName:p.displayName})));}));
  app.post("/api/posts/publish",optional,required,express.raw({limit:"100mb",type:"*/*"}),asyncHandler(async(req,res)=>{if(!Buffer.isBuffer(req.body)||!req.body.length)return apiError(res,400,"INVALID_MEDIA");const type=req.get("content-type")?.split(";",1)[0]??"",caption=req.get("x-onlykas-caption")??"",price=req.get("x-onlykas-price")??"",hint=mediaHintError(type,req.body.length);if(hint)return apiError(res,422,"INVALID_MEDIA",hint);const priceSompi=parseKasToSompi(price);const errors:string[]=priceSompi?[]:[COPY.invalidPrice];if(!caption.trim())errors.push("Caption must be between 1 and 280 characters.");if([...caption.trim()].length>280)errors.push("Caption must be between 1 and 280 characters.");if(errors.length)return res.status(400).json({error:"INVALID_POST",errors});const dir=await mkdtemp(join(tmpdir(),"onlykas-publish-")),source=join(dir,"media");let key:string|undefined;try{await writeFile(source,req.body);const media=await verifyMediaFile(source);key=`media/blake3/${media.digest.slice(0,2)}/${media.digest}`;await d.storage.putFile(key,source,media.mediaType);const post:Post={id:randomUUID(),creator:req.walletSession!.address,caption:normalizePostText(caption),priceSompi:priceSompi!.toString(),mediaType:media.mediaType,mediaSize:media.size,mediaDigest:media.digest,mediaKey:key,publishedAt:now()};if(await d.store.publishPost(post)==="MEDIA_DIGEST_CONFLICT"){await d.storage.delete(key).catch(()=>undefined);return apiError(res,409,"MEDIA_ALREADY_PUBLISHED");}res.status(201).json({id:post.id});}catch(e){if(e instanceof MediaValidationError)return apiError(res,422,e.category);if(key)await d.storage.delete(key).catch(()=>undefined);throw e;}finally{await rm(dir,{recursive:true,force:true});}}));
    app.get("/api/creators/:address",optional,asyncHandler(async(req,res)=>{const address=param(req,"address");if(!addressPattern.test(address))return apiError(res,400,"INVALID_ADDRESS");const viewer=req.walletSession?.address,isOwner=viewer===address,posts=await d.store.creatorPosts(address),offered=Boolean(await d.store.getCreatorCovenant(address)),active=Boolean(viewer&&!isOwner&&await membershipAccess(d,address,viewer));const unlocked=isOwner||active?new Set(posts.map(p=>p.id)):viewer?await purchasedPostIds(d,posts,viewer):new Set<string>();res.json({address,displayAddress:shorten(address),displayName:(await d.store.getProfile(address))?.displayName??null,isOwner,membership:{offered,active},posts:posts.map(p=>postResponse(p,unlocked.has(p.id)))});}));
    app.get("/api/posts/:id",optional,asyncHandler(async(req,res)=>{const p=await d.store.getPost(param(req,"id"));if(!p)return apiError(res,404,"POST_NOT_FOUND");const viewer=req.walletSession?.address;res.json(postResponse(p,Boolean(viewer&&(viewer===p.creator||await purchaseAccess(d,p,viewer)||await membershipAccess(d,p.creator,viewer))))); }));
    app.post("/api/posts/:id/payments/prepare",optional,required,asyncHandler(async(req,res)=>{if(!d.paymentGateway)throw new HttpError(503,"PAYMENT_UNAVAILABLE");const post=await d.store.getPost(param(req,"id"));if(!post)return apiError(res,404,"POST_NOT_FOUND");const buyer=req.walletSession!.address;if(buyer===post.creator||await d.store.getPurchase(post.id,buyer))return apiError(res,409,"ALREADY_UNLOCKED");try {const prepared=await d.paymentGateway.prepare(post,buyer);if(prepared.amountSompi!==post.priceSompi||prepared.creator!==post.creator)return apiError(res,422,"PAYMENT_TEMPLATE_INVALID");await d.store.prunePreparedPayments(now());const id=randomUUID();await d.store.savePreparedPayment({id,...prepared,postId:post.id,buyer,expiresAt:now()+PREPARED_TTL_MS});res.status(201).json({id,transaction:prepared.transaction,amountSompi:prepared.amountSompi});}catch(e){if(e instanceof Error&&e.message==="INSUFFICIENT_FUNDS")return apiError(res,422,"INSUFFICIENT_FUNDS",COPY.insufficientFunds);throw e;}}));
    app.post("/api/payments/:id/finalize",optional,required,asyncHandler(async(req,res)=>{if(!d.paymentGateway)throw new HttpError(503,"PAYMENT_UNAVAILABLE");const id=param(req,"id"),prepared=await d.store.getPreparedPayment(id,now());if(!prepared||prepared.buyer!==req.walletSession!.address)return apiError(res,404,"PAYMENT_NOT_FOUND");const body=z.object({signedTransaction:z.string().min(1)}).parse(req.body),submission=await d.paymentGateway.submit(prepared,body.signedTransaction);if(submission.isAccepted!==true||!submission.transactionId){await d.store.deletePreparedPayment(id);if(submission.isAccepted===null)return res.status(202).json({state:"PENDING",message:COPY.purchasePending,transactionId:submission.transactionId});return res.status(422).json({state:"REJECTED",message:COPY.transactionRejected,rejection:submission.rejection});}const purchase={postId:prepared.postId,buyer:prepared.buyer,transactionId:submission.transactionId};if(!await d.store.createPurchase(purchase))return apiError(res,409,"PURCHASE_EXISTS");await d.store.deletePreparedPayment(id);res.status(201).json({state:"CONFIRMED",transactionId:purchase.transactionId,message:COPY.unlocked});}));
    app.post("/api/membership/offers/prepare",optional,required,asyncHandler(async(req,res)=>{if(!d.membershipGateway)throw new HttpError(503,"MEMBERSHIP_UNAVAILABLE");const creator=req.walletSession!.address;if(await d.store.getCreatorCovenant(creator))return apiError(res,409,"MEMBERSHIP_OFFER_EXISTS");const value=await d.membershipGateway.prepareOffer(creator),id=randomUUID();logger.info("membership_prepare",{requestId:req.requestId,kind:"offer",signInputs:value.signInputs});await d.store.prunePreparedMemberships(now());await d.store.savePreparedMembership({id,...value,creator,buyer:creator,kind:"offer",expiresAt:now()+PREPARED_TTL_MS});res.status(201).json({id,transaction:value.transaction,signInputs:value.signInputs});}));
    app.post("/api/membership/offers/:id/finalize",optional,required,asyncHandler(async(req,res)=>{if(!d.membershipGateway)throw new HttpError(503,"MEMBERSHIP_UNAVAILABLE");const value=await d.store.getPreparedMembership(param(req,"id"),now());if(!value||value.kind!=="offer"||value.creator!==req.walletSession!.address)return apiError(res,404,"MEMBERSHIP_OFFER_NOT_FOUND");const body=z.object({signedTransaction:z.string().min(1)}).parse(req.body);logger.info("membership_finalize",{requestId:req.requestId,kind:"offer",signInputs:value.signInputs});const submission=await d.membershipGateway.submit(value,body.signedTransaction);if(submission.isAccepted!==true||!submission.transactionId){await d.store.deletePreparedMembership(param(req,"id"));return res.status(submission.isAccepted===null?202:422).json({state:submission.isAccepted===null?"PENDING":"REJECTED",transactionId:submission.transactionId,rejection:submission.rejection});}const mapping:CreatorCovenant={creator:value.creator,covenantId:value.covenantId};await d.store.saveCreatorCovenant(mapping);await d.store.deletePreparedMembership(param(req,"id"));res.status(201).json({state:"CONFIRMED",transactionId:submission.transactionId,covenantId:value.covenantId});}));
    app.post("/api/membership/:creator/prepare",optional,required,asyncHandler(async(req,res)=>{if(!d.membershipGateway)throw new HttpError(503,"MEMBERSHIP_UNAVAILABLE");const creator=param(req,"creator");if(!addressPattern.test(creator))return apiError(res,400,"INVALID_ADDRESS");const buyer=req.walletSession!.address;if(buyer===creator)return apiError(res,409,"CREATOR_CANNOT_SUBSCRIBE");const mapping=await d.store.getCreatorCovenant(creator);if(!mapping)return apiError(res,404,"MEMBERSHIP_OFFER_NOT_FOUND");const value=await d.membershipGateway.prepareMint(creator,buyer,mapping.covenantId),id=randomUUID();logger.info("membership_prepare",{requestId:req.requestId,kind:"purchase",signInputs:value.signInputs});await d.store.prunePreparedMemberships(now());await d.store.savePreparedMembership({id,...value,creator,buyer,kind:"purchase",expiresAt:now()+PREPARED_TTL_MS});res.status(201).json({id,transaction:value.transaction,signInputs:value.signInputs});}));
    app.post("/api/membership/purchases/:id/finalize",optional,required,asyncHandler(async(req,res)=>{if(!d.membershipGateway||!d.membershipVerifier)throw new HttpError(503,"MEMBERSHIP_UNAVAILABLE");const id=param(req,"id"),value=await d.store.getPreparedMembership(id,now());if(!value||value.kind!=="purchase"||value.buyer!==req.walletSession!.address)return apiError(res,404,"MEMBERSHIP_PURCHASE_NOT_FOUND");const body=z.object({signedTransaction:z.string().min(1)}).parse(req.body);logger.info("membership_finalize",{requestId:req.requestId,kind:"purchase",signInputs:value.signInputs});const submission=await d.membershipGateway.submit(value,body.signedTransaction);if(submission.isAccepted!==true||!submission.transactionId){await d.store.deletePreparedMembership(id);return res.status(submission.isAccepted===null?202:422).json({state:submission.isAccepted===null?"PENDING":"REJECTED",transactionId:submission.transactionId,rejection:submission.rejection});}const check=await d.membershipVerifier.verifyUtxo(submission.transactionId,value.memberOutputIndex!,value.buyer,value.covenantId,value.creator);if(check.status!=="VALID"){await d.store.deletePreparedMembership(id);return res.status(422).json({state:"REJECTED",error:"MEMBERSHIP_NOT_CONFIRMED",membership:check});}await d.store.createMembershipPurchase({transactionId:submission.transactionId,buyer:value.buyer});await d.store.deletePreparedMembership(id);res.status(201).json({state:"CONFIRMED",transactionId:submission.transactionId,membership:check});}));
   app.post("/api/membership/purchases/confirm",optional,required,asyncHandler(async(req,res)=>{if(!d.membershipVerifier)throw new HttpError(503,"VERIFY_UNAVAILABLE");const b=z.object({creator:z.string().regex(addressPattern),transactionId:z.string().regex(/^[0-9a-f]{64}$/i),outputIndex:z.literal(1)}).parse(req.body),mapping=await d.store.getCreatorCovenant(b.creator);if(!mapping)return apiError(res,404,"COVENANT_NOT_FOUND");const buyer=req.walletSession!.address,check=await d.membershipVerifier.verifyUtxo(b.transactionId,b.outputIndex,buyer,mapping.covenantId,b.creator);if(check.status!=="VALID")return res.status(422).json({error:"MEMBERSHIP_NOT_CONFIRMED",membership:check});await d.store.createMembershipPurchase({transactionId:b.transactionId,buyer});res.status(201).json(check);}));
  app.get("/api/verify/membership/address/:address",asyncHandler(async(req,res)=>{if(!d.membershipVerifier)throw new HttpError(503,"VERIFY_UNAVAILABLE");const address=param(req,"address");if(!addressPattern.test(address))return apiError(res,400,"INVALID_ADDRESS");const owner=ownerFrom(req);if(owner==="invalid")return apiError(res,400,"INVALID_ADDRESS");const memberships=await d.membershipVerifier.verifyAddress(address,owner),body:MembershipAddressVerificationResponse={address,verifiedAt:new Date(now()).toISOString(),valid:memberships.some(x=>x.status==="VALID"),memberships};res.json(body);}));
  app.get("/api/verify/membership/utxo/:transactionId/:outputIndex",asyncHandler(async(req,res)=>{if(!d.membershipVerifier)throw new HttpError(503,"VERIFY_UNAVAILABLE");const tx=param(req,"transactionId"),index=Number(param(req,"outputIndex"));if(!/^[0-9a-f]{64}$/i.test(tx)||!Number.isInteger(index)||index<0)return apiError(res,400,"INVALID_REQUEST");const owner=ownerFrom(req);if(owner==="invalid")return apiError(res,400,"INVALID_ADDRESS");res.json(await d.membershipVerifier.verifyUtxo(tx,index,owner));}));
    app.all("/api/posts/:id/media",optional,required,asyncHandler(async(req,res)=>{if(req.method!=="GET"&&req.method!=="HEAD")return res.status(405).end();const p=await d.store.getPost(param(req,"id"));if(!p)return apiError(res,404,"POST_NOT_FOUND");const viewer=req.walletSession!.address;if(viewer!==p.creator&&!await purchaseAccess(d,p,viewer)&&!await membershipAccess(d,p.creator,viewer))return apiError(res,403,"MEDIA_FORBIDDEN");const range=parseRange(req.headers.range,p.mediaSize);if(range==="invalid"){res.setHeader("Content-Range",`bytes */${p.mediaSize}`);return res.status(416).end();}const object=await d.storage.readRange(p.mediaKey,range?.start,range?.end);res.setHeader("Accept-Ranges","bytes");res.setHeader("Content-Type",p.mediaType);res.setHeader("Content-Length",object.bytes.byteLength);if(range){res.status(206);res.setHeader("Content-Range",`bytes ${range.start}-${range.end}/${p.mediaSize}`);}if(req.method==="HEAD")return res.end();res.send(Buffer.from(object.bytes));}));
   if(d.production){const frontend=join(import.meta.dirname,"../../frontend/dist");app.use(express.static(frontend));app.get("/{*path}",(_,res)=>res.sendFile(join(frontend,"index.html")));}app.use((e:unknown,req:Request,res:Response,next:NextFunction)=>{void next;if(e instanceof z.ZodError)return apiError(res,400,"INVALID_REQUEST");if(e instanceof HttpError)return apiError(res,e.status,e.code);logger.error("request_failed",{requestId:req.requestId,method:req.method,path:req.path,route:routePattern(req),...safeError(e)});return apiError(res,503,"SERVICE_UNAVAILABLE");});return app;
}
 async function purchaseAccess(d:AppDependencies,post:Post,buyer:string){const receipt=await d.store.getPurchase(post.id,buyer);if(!receipt||!d.paymentGateway)return false;return d.paymentGateway.verifyPurchase(receipt.transactionId,buyer,post.creator,post.priceSompi);}
 async function purchasedPostIds(d:AppDependencies,posts:Post[],buyer:string){const unlocked=new Set<string>();if(!d.paymentGateway)return unlocked;const receipts=await d.store.purchasesForBuyer(buyer),byPost=new Map(receipts.map(r=>[r.postId,r]));for(const post of posts){const receipt=byPost.get(post.id);if(receipt&&await d.paymentGateway.verifyPurchase(receipt.transactionId,buyer,post.creator,post.priceSompi))unlocked.add(post.id);}return unlocked;}
 async function membershipAccess(d:AppDependencies,creator:string,buyer:string){const mapping=await d.store.getCreatorCovenant(creator);if(!mapping||!d.membershipVerifier)return false;for(const purchase of await d.store.membershipPurchases(buyer)){const check=await d.membershipVerifier.verifyUtxo(purchase.transactionId,1,buyer,mapping.covenantId,creator);if(check.status==="VALID")return true;}return false;}
function postResponse(p:Post,canView:boolean):PostResponse{return {id:p.id,creator:p.creator,caption:p.caption,priceSompi:p.priceSompi,mediaType:p.mediaType,publishedAt:new Date(p.publishedAt).toISOString(),canView};}
function profileResponse(p:Profile|null,address:string){return {address,displayAddress:shorten(address),displayName:p?.displayName??null};}function shorten(a:string){return `${a.slice(0,16)}...${a.slice(-8)}`;}function trusted(req:Request,origin:string){if(req.get("origin")!==origin)throw new HttpError(403,"ORIGIN_MISMATCH");}function param(req:Request,n:string){const v=req.params[n];if(typeof v!=="string")throw new HttpError(400,"INVALID_REQUEST");return v;}function ownerFrom(req:Request){const v=req.query.owner;if(v===undefined)return undefined;if(typeof v!=="string"||!v)return "invalid";return addressPattern.test(v)?v:"invalid";}
  function setCookie(res:Response,id:string,production:boolean){res.cookie(sessionCookie,id,cookieOptions(production));}function cookieOptions(production:boolean){return {httpOnly:true,secure:production,sameSite:"strict" as const,maxAge:SESSION_IDLE_TTL_MS,path:"/"};}function apiError(res:Response,status:number,code:string,message?:string){res.locals.apiErrorCode=code;return res.status(status).json({error:code,message:message??`${code.toLowerCase().replaceAll("_"," ")}.`});}function routePattern(req:Request){const route=req.route?.path;return typeof route==="string"?`${req.baseUrl}${route}`:undefined;}class HttpError extends Error{constructor(readonly status:number,readonly code:string){super(code);}}function asyncHandler(fn:(req:Request,res:Response,next:NextFunction)=>Promise<unknown>){return(req:Request,res:Response,next:NextFunction)=>{void fn(req,res,next).catch(next);};}
function parseRange(header:string|undefined,size:number):{start:number;end:number}|null|"invalid"{if(!header)return null;const m=/^bytes=(\d*)-(\d*)$/.exec(header);if(!m||(!m[1]&&!m[2]))return "invalid";const start=m[1]?Number(m[1]):Math.max(0,size-Number(m[2])),end=m[2]&&m[1]?Number(m[2]):size-1;if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start<0||start>=size||end<start)return "invalid";return {start,end:Math.min(end,size-1)};}
