apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: onlykas-secrets
  namespace: onlykas
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: onlykas-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: onlykas/DATABASE_URL
    - secretKey: DATABASE_AUTH_TOKEN
      remoteRef:
        key: onlykas/DATABASE_AUTH_TOKEN
    - secretKey: R2_ENDPOINT
      remoteRef:
        key: onlykas/R2_ENDPOINT
    - secretKey: R2_ACCESS_KEY_ID
      remoteRef:
        key: onlykas/R2_ACCESS_KEY_ID
    - secretKey: R2_SECRET_ACCESS_KEY
      remoteRef:
        key: onlykas/R2_SECRET_ACCESS_KEY
