apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: onlykas
  namespace: onlykas
  labels:
    app.kubernetes.io/name: onlykas
    app.kubernetes.io/component: metrics
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: onlykas
      app.kubernetes.io/component: metrics
  endpoints:
    - port: metrics
      path: /metrics
      interval: 20s
