export const COPY = {
  authPrompt:
    "Connect to OnlyKas. This only identifies your wallet. No KAS will be sent.",
  kaswareMissing:
    "Open Kasware to connect. Your wallet is used to identify you and approve payments.",
  wrongNetwork:
    "Your wallet is on the wrong network. Switch networks in Kasware and try again.",
  walletCancelled: "Wallet connection cancelled.",
  signInCancelled: "Sign-in cancelled.",
  verificationFailed: "OnlyKas could not verify this wallet. Try again.",
  serverDown: "Server is down. Try again shortly.",
  unsupportedMedia: "Choose a JPEG, PNG, WebP, MP4, or WebM file.",
  imageTooLarge: "Images can be up to 25 MB.",
  videoTooLarge: "Videos can be up to 100 MB.",
  malformedMedia: "This file cannot be played by OnlyKas.",
  uploadFailed: "Upload failed. Try again.",
  invalidPrice: "Enter a KAS price greater than zero, using up to 8 decimal places.",
  permanence:
    "Publishing is permanent. The media, details, and price cannot be changed.",
  publishingCancelled: "Publishing cancelled.",
  publishing: "Publishing...",
  published: "Published.",
  publishFailed: "Post was not published. Try again.",
  mediaAlreadyPublished:
    "This photo or video has already been published. Choose another.",
  mediaUnavailable:
    "This media is temporarily unavailable. Your purchase is unchanged.",
  unlockPrompt:
    "You are supporting this creator with {price} KAS. Kasware will show the network fee before you approve. This payment cannot be reversed.",
  paymentCancelled: "Payment cancelled.",
  unlocked: "Unlocked.",
  insufficientFunds: "You need enough KAS for the post and the network fee.",
  transactionRejected: "Transaction rejected. No access was granted. Try again.",
  purchasePending: "Purchase pending. Do not pay again.",
  paymentTimedOut:
    "We couldn't confirm the payment. Check the transaction and try again.",
  accessVerificationFailed: "OnlyKas can't verify access right now. Try again.",
  unlockRequired: "Unlock this post to view it.",
  invalidCreatorAddress: "Enter a complete Kaspa testnet address.",
  offerInvalid: "Add a price and a warm note for your circle.",
  offerMembershipTitle: "Your inner circle",
  offerMembershipIntro: "A private day of access for the people who support you most.",
  offerDescriptionLabel: "What they get",
  offerDescriptionHint: "Welcome them warmly — say what the day holds.",
  offerMembershipPermanence:
    "Once it's open, your price and your words stay as they are. Choose well.",
  membershipUnavailable: "Membership is catching up. Try again in a moment.",
  becomeMemberFor: "Become a member for {price}",
  renewMembershipFor: "Renew for {price}",
  membershipPrompt:
    "This sends {price} KAS and opens one day of access. The network fee shows in Kasware before you approve. It can't be undone.",
  membershipSigning: "Approve in Kasware",
  membershipConfirming: "Making it official...",
  membershipPending: "On its way — nothing more to do.",
  membershipLive: "You're a member.",
  membershipExpired: "Your time as a member has passed.",
  membershipRejected:
    "Nothing went through, and nothing was charged. Whenever you're ready, try again.",
  membershipNoOffer: "This creator hasn't opened their circle yet.",
  membershipActiveUntil: "Active until {date}.",
  membershipExpiredOn: "It ended {date}.",
  membershipPriceMismatch:
    "The price changed while you were joining. Take a fresh look and try again.",
  membershipNoteOpen: "The door is open. One day at a time.",
  membershipNoteMember: "Renew any time. Pass it on when you're ready.",
  membershipNoteLapsed: "The door is still open.",
  transferTitle: "Pass it on",
  transferIntro:
    "A friend can take over your remaining day. You set the price — the creator keeps 10%, the rest is yours.",
  transferRecipientLabel: "Who gets it",
  transferRecipientHint: "Their Kaspa address",
  transferSaleLabel: "Your price",
  transferSignPrompt:
    "Sign in Kasware to pass it on. The creator keeps 10% and {seller} KAS comes to you. It can't be undone.",
  transferSigning: "Approve in Kasware",
  transferConfirming: "Passing it on...",
  transferPending: "On its way — nothing more to do.",
  transferSent: "Done. Your pass has a new home.",
  transferRejected:
    "Nothing went through, and nothing was charged. Whenever you're ready, try again.",
  transferInvalidRecipient: "Enter a complete Kaspa address.",
  transferInvalidAmount: "Set a price above zero.",
  transferExpired: "This membership has expired and cannot be resold.",
  transferNotHolder: "Only the current holder can resell this membership.",
  transferUnavailable: "Membership transfers are temporarily unavailable. Try again.",
  transferNotFound: "This transfer could not be found.",
  feedbackButton: "Feedback",
  feedbackDialogTitle: "Tell us anything",
  feedbackLabel: "A bug, an idea, or something that felt confusing.",
  feedbackHint: "Anonymous. Sent straight to us.",
  feedbackPlaceholder: "What should we improve?",
  feedbackSend: "Send feedback",
  feedbackThanks: "Thanks. Your feedback was sent.",
  feedbackRequired: "Write a few words first.",
  feedbackFailed: "Could not send feedback. Please try again.",
} as const;
